### PR TITLE
Replace Kirby's default language menu

### PR DESCRIPTION
**Pull request by Daandelange**
Hello again,

Digging into Kirby I figured that it uses [vue-simple-portal](https://github.com/LinusBorg/vue-simple-portal) internally.
So I had to try it out with this plugin. I made a "portaled" option.
I hope you are willing to merge it.   
*I've tried to keep your coding style this time; probably still too much comments*.

#### Breaks and/or fixes :
 - Clicking on the current lang doesn't reload the page anymore.
 - Ensure that click events don't bubble by adding `@click.stop=`.
 - k-buttons are now made responsive (changes layout on small screens).  
   (The layout looks good with 3 languages or less, more might cause issues).
 
#### New Features :
 - Adds a compact mode putting the language options in a submenu.
 - Pure Portal Power : Adds the possibility to render the compact view by replacing Kirby's default language switcher.
 - Adds more html classes to elements (so custom styling becomes easier).

Also:
 - What about wrapping the HTML + JS in a Vue component file ? Html editing is way easier that way.
 - I've tried to keep the same template for both portaled and non-portaled, but that didn't keep the code simple so I ended up adding a compact mode. *Edit: I've found a way to group them again except for the submenu, see c18662c*.
 - Not sure how well these changes apply to pre-3.6 installations. (untested)
 
 image
 
 <details>
  <summary>Moar Images :boom:</summary>
  
Tiny :
image
Small:
image
CompactView:
image
</details>

### CODE REVIEW

**Comment by flokosiol** [comment]
Hey @Daandelange,

Thanks again for your contribution! If you keep going at this rate, soon I won't be able to call the plugin my own anymore. 😜 

Replacing the default language switcher is a really nice idea. I will definitely take a look at your code. But I'm afraid I won't get a chance to look at everything before the weekend.

**Comment by Daandelange** [comment]
Haha, no worries, take your time.

Taking this further, I almost turned it into a more global [PanelCreated](https://getkirby.com/docs/reference/plugins/extensions/created) extension; but if the K2 feature (the translated flag) returns, a field remains more appropriate.

**Comment by Daandelange** [comment]
I just found an issue with the portal mode when used together with tabs or when conditions, the translation field can be hidden which causes the replaced/portaled page translation settings to vanish too... so this might not be ready to merge yet.

**Comment by flokosiol** [comment]
Thanks for the update. Unfortunately I have almost no spare time to maintain my open source stuff at the moment, including your (nevertheless appreciated) contributions. 

But … maybe you are interested in maintaining this plugin? If you like, I am happy to transfer the repo to your account.

**Comment by Daandelange** [comment]
Could be, I have some spare time now to get this to K3; long-term maintenance I don't know but I can always transfer or archive it later.
As your plugin has never really supported K3, wouldn't it make more sense if I "officialise" my clone/fork as the k3 version while you archive (or keep?) this repo for k2 ?
Co-ownership is also an option to me.

**Comment by flokosiol** [comment]
Separating K2 and K3 is a really good idea. Your clone should be the official K3 version. 

I will try to find out how to update my composer file to let people know about the switch but I'm sure there are options to set deprecation messages. 

Let me know as soon as your repo is ready for the public and I will set mine as deprecated and link to yours. Additionally I will post it on Discord and set up a short tweet. 

Thanks a lot for keeping this alive! ❤️

**Comment by Daandelange** [comment]
I'll add a few changes before pushing this to composer but it's on the way.

By the way, I've never really used that "translated" function marker, but I've read a lot of people were using it.
What was it about ? A "simple" checkbox field-value that one checks when a translation is translation-reviewed (or automatically on `translation.save()` ?), and it goes unchecked when the default lang is saved ?

**Comment by flokosiol** [comment]
We had a long discussion on the forum (back in 2016 😱) and I finally decided to keep it as a simple checkbox which can be checked/unchecked manually.

https://forum.getkirby.com/t/translations-keep-track-of-translation-status/4338/28?u=flokosiol

**Comment by Daandelange** [comment]
I think it's quite ready on my side for closing this. Thanks for your help ! 🚀 

Would you like any information added / removed from the k3 clone ? [Here for example](https://github.com/Daandelange/k3-translations/blob/62c119810fd872176c55d0efb6fc6c647f6a1f77/composer.json#L10-L12).

It's alpha until there's some working feedback, but it should work well already.
https://github.com/Daandelange/k3-translations

**Comment by flokosiol** [comment]
Awesome! Thanks for taking care of this! Everything's fine for me.

I'll close this here, change the README file and check out if it's possible to include a depreciation message via composer.

**Pull request closed without merging**
